# Generated by Django 4.2.7 on 2023-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_contrato', models.CharField(max_length=25)),
                ('cargo', models.CharField(max_length=25)),
                ('cuoc', models.IntegerField()),
                ('salario', models.IntegerField()),
                ('tipo_empleo', models.CharField(max_length=25)),
                ('n_vacantes', models.IntegerField()),
                ('n_postulaciones', models.IntegerField()),
            ],
        ),
    ]
